ControlWork8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('products/add/', ProductCreateView.as_view(), name='product_add'),
    path('product/<int:pk>/review/add/', ReviewCreateView.as_view(), name='review_add'),
    path('categor_add/', CategoryCreateView.as_view(), name='category_add'),
    path('users/', include('users.urls', namespace='users')),

    path('product/<int:pk>', ProductDetailView.as_view(), name='product_view'),
    path('product/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('view_comments/', reviewlist, name='view_review'),
    path('review/delete/<int:pk>/', ReviewDeleteView.as_view(), name='review_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products.views import *

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),
]

users/urls.py
from django.urls import path
from users.views import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification')
]

products/models.py
from django.db import models
from users.models import User


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, default='Other')
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500, null=True, blank=True, verbose_name='Описание продукта')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    image = models.ImageField(null=True, upload_to='products_images', verbose_name='Картинка')

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return f'Продукт: {self.name} | Категория {self.category.name}'


class Review(models.Model):
    RATING_CHOICES = [
        ('0', 'Нет оценки'),
        ('1', 'Не советую'),
        ('2', 'На небольшой бюджет'),
        ('3', 'Можно пользоваться'),
        ('4', 'Лучший выбор'),
        ('5', 'Для мажоров'),
    ]

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, null=False, related_name='review')
    product = models.ManyToManyField(to=Product) # Вначале был ForeignKey и все работало прекрасно
    description = models.TextField(max_length=500, null=True, blank=True, verbose_name='Отзыв')
    created_timestamp = models.DateTimeField(auto_now_add=True)
    rating = models.CharField(max_length=1, choices=RATING_CHOICES, default='0')

    def __str__(self):
        return f'Отзыв для {self.user.username} {self.user.email} ' \
               f'| Продукт {self.product.name} | Оценка {self.rating}'

products/forms.py
from django import forms
from .models import Product, ProductCategory, Review


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'category', 'price', 'image']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = ['name', 'description']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['user', 'product', 'description', 'rating']


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти товар")

products/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.http import urlencode
from django.views.generic.base import TemplateView
from django.views.generic import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from products.forms import *
from products.models import ProductCategory, Product, Review
from django.db.models.functions import Lower
from common.views import TitleMixin
from django.shortcuts import render, get_object_or_404


class IndexView(TitleMixin, TemplateView):
    template_name = 'index.html'
    title = 'Отзовик'


class ProductsListView(TitleMixin, ListView):
     model = Product
     template_name = 'products.html'
     paginate_by = 6
     paginate_orphans = 1
     title = 'Каталог товаров'
     ordering = ['name']

     def get(self, request, *args, **kwargs):
         self.form = self.get_search_form()
         self.search_value = self.get_search_value()
         return super().get(request, *args, **kwargs)

     def get_queryset(self):
         queryset = super(ProductsListView, self).get_queryset().order_by(Lower('name'))
         category_id = self.kwargs.get('category_id')
         if self.search_value:
             query = Q(name__icontains=self.search_value) | Q(description__icontains=self.search_value)
             queryset = queryset.filter(query)
         return queryset.filter(category_id=category_id) if category_id else queryset

     def get_context_data(self, *, object_list=None, **kwargs):
         context = super(ProductsListView, self).get_context_data(object_list=object_list, **kwargs)
         context['form'] = self.form
         context['categories'] = ProductCategory.objects.all().order_by('-name')
         if self.search_value:
             context['query'] = urlencode({'search': self.search_value})
         return context

     def get_search_form(self):
         return SimpleSearchForm(self.request.GET)

     def get_search_value(self):
         if self.form.is_valid():
             return self.form.cleaned_data['search']
         return None


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product_update.html'

    def get_success_url(self):
        return reverse_lazy('product_view', args=(self.object.id,))

    def get_context_data(self, **kwargs):
        context = super(ProductUpdateView, self).get_context_data()
        context['title'] = 'Магазин - Просмотр товара'
        return context


class ProductDetailView(DetailView):
    template_name = 'product_view.html'
    model = Product


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product_add.html'
    extra_context = {'title': 'Добавить товар'}
    success_url = reverse_lazy('products:index')


class ReviewCreateView(CreateView):
    model = Review
    template_name = 'review_add.html'
    form_class = ReviewForm
    success_url = reverse_lazy('view_review')

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        comment = form.save(commit=False)
        comment.article = product
        comment.save()
        return redirect('review_add', pk=product.pk)


class ProductDeleteView(DeleteView):
    template_name = 'product_confirm_delete.html'
    model = Product
    context_object_name = 'product'
    success_url = reverse_lazy('index')


class CategoryCreateView(CreateView):
    model = ProductCategory
    form_class = CategoryForm
    template_name = 'category_add_view.html'
    extra_context = {'title': 'Добавить категорию'}
    success_url = reverse_lazy('products:index')


@login_required()
def reviewlist(request):
    reviews = Review.objects.all()
    return render(request, 'review_list.html', {'reviews': reviews})


class ReviewDeleteView(DeleteView):
    template_name = 'product_confirm_delete.html'
    model = Review
    context_object_name = 'review'
    success_url = reverse_lazy('index')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

   {% block css %} {% endblock %}

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Отзовик контрольной работы №8</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог товаров отеля Континенталь<i class="fas fa-shopping-bag"></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'view_review' %}">Стена отзывов<i class="fa-list"></i> </a>
                </li>
            {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Профиль</a>
                        </li>
                     {% if user.is_superuser or user.is_staff %}
                        <li>
                            <a class="dropdown-item" href="{% url 'product_add' %}">Добавить товар</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'category_add' %}">Добавить категорию</a>
                        </li>
                            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админка</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
                {% else %}
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти<i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %} " crossorigin="anonymous"></script>

</body>

</html>

templates/category_add_view.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
       <form action="{% url 'category_add' %}" method="post">>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <br>
                    Добро пожаловать в электронный журнал отзывов! <br>Итог второго месяца Django.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                     {% if user.is_authenticated %}
                    <a id="start-purchase-link" href="{% url 'review_add' user.id %}">
                        Оставить отзыв
                    </a>
                    {% else %} <a id="start-purchase-link" href="{% url 'users:login' %}">
                          Войти
                    </a>
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/product_add.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
       <form action="{% url 'product_add' %}" method="post" enctype="multipart/form-data">>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>
{% endblock %}

templates/product_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
      <form method="post">{% csrf_token %}
        <p>Вы уверены, что хотите удалить данный товар? "{{ object }}"?</p>
        <input type="submit" value="Подтвердить">
        </form>
{% endblock %}

templates/product_update.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
       <form action="{% url 'product_update' product.id %}" method="post" enctype="multipart/form-data">>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>
{% endblock %}

templates/product_view.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="col-lg-4 col-md-8 mb-4">
                    <div class="card h-200">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price }} фитиль</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <a href="{% url 'products:index' %}">Вернуться</a>
                        <a href="{% url 'product_update' product.id %}">Изменить</a>
                        <a href="{% url 'product_delete' product.id %}">Удалить</a>
                    </div>
                </div>
{% endblock %}

templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
 <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Товары</h1>
            <div class="list-group">
                {% for category in categories %}
                <a href="{% url 'products:category' category.id %}" class="list-group-item">
                    {{ category.name }}
                </a>
                {% endfor %}
            </div>
            <form class="text-center" action="" method="GET">
            <label for="{{ form.search.id_for_label }}">{{ form.search.label }}:</label>
                {{ form.search }}
            <input type="submit" value="Search">
            {% for error in form.search.errors %}
            <p class="form-error">{{ error }}</p>
             {% endfor %}
            </form>
        </div>

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/1.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/2.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/3.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for product in object_list %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="{% url 'product_view' product.id %}">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{% url 'product_view' product.id %}">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.category.name }}</h5>
                            <h5>{{ product.price }} фитиль</h5>
                            <p class="card-text">{{ product.description |truncatechars:30 }}</p>
                        </div>
                        <a href="{% url 'product_view' product.id %}">Подробнее</a>
                        <div class="card-footer text-center">
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
            {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link"
                           href="?{% if query %}{{ query }}&{% endif %}{% if page_obj.has_previous %}= {% url 'products:paginator' page_obj.previous_page_number %} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">
                            Предыдущая
                        </a>

                    </li>
                    {% for page in paginator.page_range %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'products:paginator' page %}">
                                {{ page }}
                            </a>
                        </li>
                    {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link"
                           href="?{% if query %}{{ query }}&{% endif %}={% if page_obj.has_next %}{% url 'products:paginator' page_obj.next_page_number %}{% else %} # {% endif %}">
                            Следующая
                        </a>
                    </li>
                </ul>
            </nav>
            {% endif %}

        </div>

    </div>

</div>
{% endblock %}

{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Attractor School.ControlWork 8.</p>
    </div>
</footer>
{% endblock %}

templates/review_add.html
{% extends 'base.html' %}


{% block title %}Create{% endblock %}

{% block content %}
    <h1>Добавить отзыв</h1>
    {% include 'partial/form.html' with action_url="" form_method='post' %}
{% endblock %}

templates/review_delete.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
      <form method="post">{% csrf_token %}
        <p>Вы уверены, что хотите удалить данный отзыв? "{{ object }}"?</p>
        <input type="submit" value="Подтвердить">
        </form>
{% endblock %}

templates/review_list.html
{% extends "base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            {% if comments %}
                 <h1> Общее количество отзывов - {{ reviews.count }}</h1>
            {% else %}
                           <h1>Текущие отзывы</h1>
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
        {% if reviews %}
            <div class="list-group">
                {% for review in reviews  %}
                        <b>Отзыв {{ review.product.name }}<br>
                            <img src="{{ review.product.image.url }}" alt=""><br> Автор- {{ review.user }}</b>
                            ({{ review.user.email }}) "{{ review.description }}" Оценка - {{ review.rating }} <br>
                     <form method="post">
                   <a href="{% url 'review_delete' review.id %}">Удалить</a>
                     </form>
                           <hr>
                {% endfor %}

            </div>
        {% else %}
            <div class="text-center">
                <h2>У вас не пока комментариев</h2>
            <br>
            <a role="button" class="btn btn-primary" href="{% url 'createreview' %}">Новый отзыв</a>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}